version: '3.0'
services:
    redis:
        image: redis:alpine
        container_name: manuelkleinert-redis
        network_mode: bridge

    db:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        container_name: manuelkleinert-mysql
        command: --init-file /data/application/init.sql
        volumes:
            - ./docker/mysql_init.sql:/data/application/init.sql
            - manuelkleinert-database:/var/lib/mysql
            - .:/var/www/html
        network_mode: bridge
        environment:
            - MYSQL_ROOT_PASSWORD=ROOT
            - MYSQL_DATABASE=pimcore
            - MYSQL_USER=pimcore
            - MYSQL_PASSWORD=pimcore

    adminer:
        image: adminer
        container_name: manuelkleinert-adminer
        restart: always
        volumes:
            - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/uploads.ini
        ports:
            - "2001:8080"
        links:
            - db:db
        network_mode: bridge

    php:
        image: pimcore/pimcore:PHP7.4-apache
        container_name: manuelkleinert-php
        volumes:
            - ~/.composer:/root/composer
            - .:/var/www/html:cached
            - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        ports:
            - "2000:80"
        links:
            - db:db
            - redis:redis
        network_mode: bridge

    php-debug:
        image: pimcore/pimcore:PHP7.4-apache-debug
        container_name: manuelkleinert-php-debug
        volumes:
            - ~/.composer:/root/composer
            - .:/var/www/html:cached
            - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        ports:
            - "2006:80"
        links:
            - db:db
            - redis:redis
        network_mode: bridge

volumes:
    manuelkleinert-database:
