version: '3.0'
services:
    redis:
        image: redis:alpine
        container_name: manuelkleinert-redis
        network_mode: bridge

    db:
        image: mariadb:10
        container_name: manuelkleinert-mariadb
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_general_ci, --innodb-file-format=Barracuda, --innodb-large-prefix=1, --innodb-file-per-table=1]
        volumes:
            - manuelkleinert-database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=ROOT
            - MYSQL_DATABASE=pimcore
            - MYSQL_USER=pimcore
            - MYSQL_PASSWORD=pimcore
        network_mode: bridge

    adminer:
        image: adminer
        container_name: manuelkleinert-adminer
        restart: always
        volumes:
            - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/uploads.ini
        ports:
            - "2001:8080"
        links:
            - db:db
        network_mode: bridge

    php:
        image: pimcore/pimcore:PHP7.4-apache
        container_name: manuelkleinert-php
        volumes:
            - ~/.composer:/root/composer
            - .:/var/www/html:cached
            - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        ports:
            - "2000:80"
        links:
            - db:db
            - redis:redis
        network_mode: bridge

    php-debug:
        image: pimcore/pimcore:PHP7.4-apache-debug
        container_name: manuelkleinert-php-debug
        volumes:
            - ~/.composer:/root/composer
            - .:/var/www/html:cached
            - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        ports:
            - "2006:80"
        links:
            - db:db
            - redis:redis
        network_mode: bridge

volumes:
    manuelkleinert-database:
