version: '2.0'
services:
  redis:
    image: redis:alpine
    container_name: manuelkleinert-redis

  db:
    image: mariadb:10.1
    container_name: manuelkleinert-mariadb
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb_large_prefix=1]
    volumes:
      - manuelkleinert-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore

#  node:
#    build: .docker/node
#    container_name: manuelkleinert-node
#    volumes:
#      - .:/var/www/html:cached

  adminer:
    image: adminer
    container_name: manuelkleinert-adminer
    restart: always
    volumes:
      - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 2001:8080

  php:
    build: ./.docker/PHP7.2-apache
#    image: dpfaffenbauer/pimcore-docker-php-fpm:PHP7-apache
    container_name: manuelkleinert-php
    volumes:
      - ~/.composer:/root/composer
      - .:/var/www/html:cached
      - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    ports:
      - "2000:80"
    links:
     - db:db
     - redis:redis

volumes:
  manuelkleinert-database:
